### PR TITLE
Accessibility metadata + small updates

### PR DESCRIPTION
**Pull request by clpetersonucf**
- Adds accessibility metadata
- Regenerated lockfile to address deprecation
- Fixed autofocus on submit dialog when in accessibility mode
- Incorporates Cay's updates for MWDK3 (via #57)
- Adds dedicated keyboard instructions dialog, reworks tab sequencing a little bit to make onboarding for screenreaders more intuitive
- Items focused with `tab`/`shift+tab` will now "peek" from the folder they're contained in if they have already been categorized. The focused item will move to the top of the stack when peeked in this manner to ensure it's always clear which one is actually focused.

### CODE REVIEW

**Review by FrenjaminBanklin — APPROVED** [review]
Everything seems to be running well.

**Review by dmols — CHANGES_REQUESTED** [review]
Widget runs great! I only noticed a few things that could potentially enhance the user experience. 

- Tabbing to an item and placing it in a folder makes the focus stay where the item used to be (when VO is on. doesn't seem to happen without); might be good to auto-focus on the next item afterwards, since VO also indicates the item has not yet been placed (when it has). Example: 
Screenshot 2023-10-31 at 11 00 29 AM

- Could the widget benefit from having keyboard navigation instructions on moving to and from a specific folder? I imagine up and down arrow keys are standard, but it might be good to add that to the aria-label? 

- There doesn't seem to be a way to move an item OUT of a folder using tabbing or directional keys. The widget only allows the user to move it to another folder, which could be confusing. I imagine an implementation of this could skew or add a lot of difficulty to the tab order, so I can take it or leave it if you feel it's not necessary.

**Comment by clpetersonucf** [comment]
> Tabbing to an item and placing it in a folder makes the focus stay where the item used to be (when VO is on. doesn't seem to happen without); might be good to auto-focus on the next item afterwards, since VO also indicates the item has not yet been placed (when it has). Example:

Part of this is just how VO renders item focus, which I'm not super concerned about since VO is intended primarily as a tool for non-sighted users. However, to facilitate better focus management for sighted users, items already placed in folders will now propagate to the top of the folder and the folder "peeks" in the same way as it does on mouseover.

> Could the widget benefit from having keyboard navigation instructions on moving to and from a specific folder? I imagine up and down arrow keys are standard, but it might be good to add that to the aria-label?

Good suggestion, added a dedicated keyboard instructions dialog.

> There doesn't seem to be a way to move an item OUT of a folder using tabbing or directional keys. The widget only allows the user to move it to another folder, which could be confusing. I imagine an implementation of this could skew or add a lot of difficulty to the tab order, so I can take it or leave it if you feel it's not necessary.

This is a design choice, since moving items out of folders isn't really a thing for non-sighted users. Non-sighted users treat the items as a flat list, with controls to categorize each item using the up and down arrow keys. "uncategorizing" an item doesn't make much sense when played in this manner.

**Review by FrenjaminBanklin — CHANGES_REQUESTED** [review]
I could see a potential future where we overengineer the whole sorting/tab order thing with this widget where tab moves between items in the current folder, left/right moves between folders, and up/down or space selects/deselects items, but the current control mechanism seems fine.

It might be useful to add conditionally-visible elements for all of the elements on the page that are in the tab order but currently exist primarily to benefit non-sighted users. Examples I noticed:
- The 'instructions' element that exists before the keyboard instructions button in the tab order but is not represented visually. Either it could be a permanent fixture on the page that pops out a tooltip or something when it receives focus (or optionally re-shows the tutorial dialog).
- The 'return to top of list' button after the final item in the list is invisible at all times - this element should probably be visible when it receives focus.
- When all items are categorized a new invisible element appears between the last item in the list and the (also invisible) 'return to top of list' button as a shortcut for submitting the attempt. Maybe this could be an invisible copy of the submit button positioned exactly the same (hacky), or as a separate element that is only visible when it receives focus (less hacky?).

The order in which things are read in the initial instructions dialog seems a little weird, but it's probably fine. When using the 'next' or 'back' buttons in the tutorial, focus kind of just floats where the previous button was since it's no longer in the DOM. It might make sense to auto-focus the 'back' button after activating the 'next' button and vice versa, so at least keyboard users know where their focus is.

Additionally, tab one time too many in the tutorial dialog dismisses it immediately. I can see the utility of this as a shortcut, but I can also see it being jarring if the instructions suddenly disappear (at least for sighted keyboard users).

**Comment by clpetersonucf** [comment]
- Removed the hidden screen reader instructions that preceded the tutorial dialog and merged them into the tutorial dialog instructions themselves. The tutorial dialog now reads back an expanded version of the instructions displayed on-screen.
- Made tutorial and keyboard dialogs modal, they must be dismissed by using the "Got it!" buttons. Elements underneath are rendered inert when dialogs are visible.
- Tutorial buttons now autofocus when the "Next" or "Back" buttons are selected.
- The hidden wraparound inputs are now visible to the user when focused.

**Review by FrenjaminBanklin — APPROVED** [review]
It occurred to me as I was going through the most recent round of changes that it might be nice to have something that selects the first uncategorized element, but that can be its own thing.

All the accessibility tweaks seem really solid and are working well.

**Review by dmols — APPROVED** [review]
I don't have any additional concerns of how the widget plays out. New changes polished the user experience even more. Great work!

**Pull request merged**
